/*
 * Lidarr
 *
 * Lidarr API docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`api_v1_mediacover_album_album_id_filename_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1MediacoverAlbumAlbumIdFilenameGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_v1_mediacover_artist_artist_id_filename_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1MediacoverArtistArtistIdFilenameGetError {
    UnknownValue(serde_json::Value),
}

pub async fn api_v1_mediacover_album_album_id_filename_get(
    configuration: &configuration::Configuration,
    album_id: i32,
    filename: &str,
) -> Result<(), Error<ApiV1MediacoverAlbumAlbumIdFilenameGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_album_id = album_id;
    let p_path_filename = filename;

    let uri_str = format!(
        "{}/api/v1/mediacover/album/{albumId}/{filename}",
        configuration.base_path,
        albumId = p_path_album_id,
        filename = crate::apis::urlencode(p_path_filename)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("apikey", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Api-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiV1MediacoverAlbumAlbumIdFilenameGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn api_v1_mediacover_artist_artist_id_filename_get(
    configuration: &configuration::Configuration,
    artist_id: i32,
    filename: &str,
) -> Result<(), Error<ApiV1MediacoverArtistArtistIdFilenameGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_artist_id = artist_id;
    let p_path_filename = filename;

    let uri_str = format!(
        "{}/api/v1/mediacover/artist/{artistId}/{filename}",
        configuration.base_path,
        artistId = p_path_artist_id,
        filename = crate::apis::urlencode(p_path_filename)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("apikey", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Api-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiV1MediacoverArtistArtistIdFilenameGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
