/*
 * Lidarr
 *
 * Lidarr API docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`api_v1_config_naming_examples_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1ConfigNamingExamplesGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_v1_config_naming_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1ConfigNamingGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_v1_config_naming_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1ConfigNamingIdGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_v1_config_naming_id_put`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1ConfigNamingIdPutError {
    UnknownValue(serde_json::Value),
}

pub async fn api_v1_config_naming_examples_get(
    configuration: &configuration::Configuration,
    rename_tracks: Option<bool>,
    replace_illegal_characters: Option<bool>,
    colon_replacement_format: Option<i32>,
    standard_track_format: Option<&str>,
    multi_disc_track_format: Option<&str>,
    artist_folder_format: Option<&str>,
    include_artist_name: Option<bool>,
    include_album_title: Option<bool>,
    include_quality: Option<bool>,
    replace_spaces: Option<bool>,
    separator: Option<&str>,
    number_style: Option<&str>,
    id: Option<i32>,
    resource_name: Option<&str>,
) -> Result<(), Error<ApiV1ConfigNamingExamplesGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_rename_tracks = rename_tracks;
    let p_query_replace_illegal_characters = replace_illegal_characters;
    let p_query_colon_replacement_format = colon_replacement_format;
    let p_query_standard_track_format = standard_track_format;
    let p_query_multi_disc_track_format = multi_disc_track_format;
    let p_query_artist_folder_format = artist_folder_format;
    let p_query_include_artist_name = include_artist_name;
    let p_query_include_album_title = include_album_title;
    let p_query_include_quality = include_quality;
    let p_query_replace_spaces = replace_spaces;
    let p_query_separator = separator;
    let p_query_number_style = number_style;
    let p_query_id = id;
    let p_query_resource_name = resource_name;

    let uri_str = format!("{}/api/v1/config/naming/examples", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_rename_tracks {
        req_builder = req_builder.query(&[("renameTracks", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_replace_illegal_characters {
        req_builder = req_builder.query(&[("replaceIllegalCharacters", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_colon_replacement_format {
        req_builder = req_builder.query(&[("colonReplacementFormat", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_standard_track_format {
        req_builder = req_builder.query(&[("standardTrackFormat", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_multi_disc_track_format {
        req_builder = req_builder.query(&[("multiDiscTrackFormat", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_artist_folder_format {
        req_builder = req_builder.query(&[("artistFolderFormat", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_include_artist_name {
        req_builder = req_builder.query(&[("includeArtistName", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_include_album_title {
        req_builder = req_builder.query(&[("includeAlbumTitle", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_include_quality {
        req_builder = req_builder.query(&[("includeQuality", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_replace_spaces {
        req_builder = req_builder.query(&[("replaceSpaces", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_separator {
        req_builder = req_builder.query(&[("separator", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_number_style {
        req_builder = req_builder.query(&[("numberStyle", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_id {
        req_builder = req_builder.query(&[("id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_resource_name {
        req_builder = req_builder.query(&[("resourceName", &param_value.to_string())]);
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("apikey", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Api-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiV1ConfigNamingExamplesGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn api_v1_config_naming_get(
    configuration: &configuration::Configuration,
) -> Result<models::NamingConfigResource, Error<ApiV1ConfigNamingGetError>> {
    let uri_str = format!("{}/api/v1/config/naming", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("apikey", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Api-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NamingConfigResource`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NamingConfigResource`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiV1ConfigNamingGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn api_v1_config_naming_id_get(
    configuration: &configuration::Configuration,
    id: i32,
) -> Result<models::NamingConfigResource, Error<ApiV1ConfigNamingIdGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!(
        "{}/api/v1/config/naming/{id}",
        configuration.base_path,
        id = p_path_id
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("apikey", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Api-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NamingConfigResource`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NamingConfigResource`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiV1ConfigNamingIdGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn api_v1_config_naming_id_put(
    configuration: &configuration::Configuration,
    id: &str,
    naming_config_resource: Option<models::NamingConfigResource>,
) -> Result<models::NamingConfigResource, Error<ApiV1ConfigNamingIdPutError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_body_naming_config_resource = naming_config_resource;

    let uri_str = format!(
        "{}/api/v1/config/naming/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("apikey", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-Api-Key", value);
    };
    req_builder = req_builder.json(&p_body_naming_config_resource);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NamingConfigResource`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NamingConfigResource`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiV1ConfigNamingIdPutError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
